spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
          google:
            client-id:
            client-secret:
app:
  login:
    redirect-url: http://localhost:3000
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080

