spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9c9e0314768baf53a6e3
            clientSecret: 7f38606f0bb143b251a90162afe22ed8b0dc473b
          google:
            client-id: 119964295255-1re8blciai1ac6cnutm16atf2ptllmv7.apps.googleusercontent.com
            client-secret: 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
app:
  login:
    redirect-url: http://localhost:3000
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080

