spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: #clientId
            clientSecret: #clientSecret
          google:
            client-id: #clientId
            client-secret: #clientSecret
app:
  logout:
    redirect-url: http://localhost:3000
  login:
    redirect-url: http://localhost:3000
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080

